language: java
script:
  - mvn test -B
notifications:
    slack:
      if: branch = master
      email:
        - darayaos18@gmail.com
      on_success: always # default: change
      on_failure: always
